### ISSUE TITLE
Install binary fails with rust 1.43

### ISSUE THREAD

**Issue by BonaBeavis** [liuchengxu/vim-clap#623]
**Environment (please complete the following information):**
 - OS: Linux
 - (Neo)Vim version: v0.5.0-dev
 - vim-clap version: 890aaca21af5ce9569d4393f72240283c198a246
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: ???  Yes

**Describe the bug**
Install binary fails with:

```
thread 'main' panicked at 'Missing expected environment variable "CARGO_PKG_LICENSE"', /home/xxx/.cargo
/registry/src/github.com-1ecc6299db9ec823/built-0.4.4/src/lib.rs:498:5
```

**Clap debug**

```

            has cargo: 1
            has maple: /home/xxx/.vim/bundle/vim-clap/target/release/maple
           maple info: version 0.1.22 (git v0.22), built for x86_64-unknown-linux-gnu by rustc 1.43.0.

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags without JSON output support
    Current sync impl: Lua
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/xxx/.vim/bundle/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
filetype off

call plug#begin('~/.vim/bundle')
Plug 'liuchengxu/vim-clap', {'do': ':Clap install-binary' }
call plug#end()

let g:python_host_prog = '/home/xxx/.virtualenvs/neovim/bin/python'
let g:python3_host_prog = '/home/xxx/.virtualenvs/neovim3/bin/python3'

syntax on
filetype plugin indent on
set hidden
```

2. :Clap install-binary

**Additional context**
Deleting build folder did not help

**Comment by liuchengxu** [comment]
What does `rustup show` say? Since you have compiled the Rust binary successfully before, can you recall any Rust lated suspicious changes you did to your system since the last compilation?

**Comment by BonaBeavis** [comment]
I do not have rustup because I installed rust from the ubuntu packages. Make also fails. I have rust only for clap installed, so I did not change my env.
I did some research, the ubuntu rust version is only 1.43.0 and CARGO_PKG_LICENSE env var was added in 1.46.0.
I set CARGO_PKG_LICENSE to foo and got another error:
```
error[E0460]: found possibly newer version of crate `std` which `autocfg` depends on
```

**Comment by liuchengxu** [comment]
Ok, upgrading your rust version to the latest should be helpful.

Or if you can checkout the latest tag and choose to use the pre-built binary from GitHub:

```vim
" :Clap install-binary[!] will always try to compile the binary locally,
" if you do care about the disk used for the compilation, try using the force download way,
" which will download the prebuilt binary even you have installed cargo.
Plug 'liuchengxu/vim-clap', { 'do': { -> clap#installer#force_download() } }
```

**Comment by BonaBeavis** [comment]
Works with 1.46
